name: Generate snake

on:
  schedule: # execute every 12 hours
    - cron: "0 0/12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-pink.svg?color_snake=#ff69b4&color_dots=rgba(0,0,0,0.1),rgba(0,0,0,0.3),rgba(0,0,0,0.5),rgba(0,0,0,0.7),rgba(0,0,0,0.9)
            
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
